name: tagdb
author: Alexander Ewetumo <trinoxf@gmail.com>
homepage: http://github.com/influx6/tagdb
version: 0.0.3
description: 'db definition capable of handling different backends'
dependencies:
  mongo_dart: any
  redis_client: any
  couchclient: any
  browser: any
  requestful: any
  ds: any
  hub: any
  lawndart: any
